import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/Splitties/refreshVersions
 */
public object Libs {
  public const val de_fayard_buildsrclibs_gradle_plugin: String =
    "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

  public const val io_freefair_lombok_gradle_plugin: String =
    "io.freefair.lombok:io.freefair.lombok.gradle.plugin:_"

  public const val io_spring_dependency_management_gradle_plugin: String =
    "io.spring.dependency-management:io.spring.dependency-management.gradle.plugin:_"

  public const val junit_platform_launcher: String = "org.junit.platform:junit-platform-launcher"

  public const val liquibase_core: String = "org.liquibase:liquibase-core"

  public const val postgresql: String = "org.postgresql:postgresql"

  public const val org_springframework_boot_gradle_plugin: String =
    "org.springframework.boot:org.springframework.boot.gradle.plugin:_"

  public const val spring_boot_starter_data_jpa: String =
    "org.springframework.boot:spring-boot-starter-data-jpa"

  public const val spring_boot_starter_test: String =
    "org.springframework.boot:spring-boot-starter-test"

  public const val spring_boot_starter_web: String =
    "org.springframework.boot:spring-boot-starter-web:_"

  public const val spring_tx: String = "org.springframework:spring-tx:_"

}
